name: Develop - DAST Validation

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  issues: write

jobs:
  dast:
    name: DAST OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar solución
        run: dotnet build --configuration Release --no-restore

      - name: Levantar API
        run: |
          dotnet run --project ./CalculadoraSimple.Api/CalculadoraSimple.Api.csproj --urls http://localhost:5000 &
          sleep 20

      - name: Verificar que la API responde
        run: curl http://localhost:5000/swagger/index.html

      - name: Ejecutar DAST con OWASP ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
          allow_issue_writing: false