name: Develop - CI Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    name: Build and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar solución
        run: dotnet build --configuration Release --no-restore

      - name: Ejecutar pruebas unitarias
        run: dotnet test --configuration Release --no-build --verbosity normal